### ISSUE TITLE
Please consider contributing some of this to our website.

### ISSUE THREAD

**Issue by nickmackenzie** [manuls/delugetricks#1]
Hello, 

I am a fellow deluge user and am creating sort of a 'go-to' docs for deluge/zoho tricks. Please consider contributing to the site!

https://github.com/nickmackenzie/dont-get-zohod

https://dont-get-zohod.vercel.app/

To contribute, its just .md files added to the pages directory. Fairly straighforward and would help grow the community.

Thanks

**Comment by manuls** [comment]
Thanks for the tip. I will check it
